### ISSUE TITLE
Deeply nested admonitions (see docs_to_test) look terrible

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#192]
Leaving out the icon in that case would improve the situation, however, the correct element for that case would seem to be a fo:block instead of a fo:list (the case we have in docs_to_test is tip/variablelist/warning/itemizedlist/table/admonition, though something similar may happen if admonitions are nested in multi-column tables)

**Comment by janajaeger** [comment]
Still relevant in 2022?

**Comment by tomschr** [comment]
Although I understand the motivation behind that, the solution would be to solve that on the validation level. Unfortunately, this use case can't be done with RELAX NG. You need some Schematron rules (which we didn't address yet).

So technically you can't really solve that. For the time being, the writers still need their brain to avoid nesting admons (and other blocks) too deep. I think, we do that already.

I see it more as a styleguide issue rather than a technical one. We should address it there (if it's not already done). For the time being, I see it as a non-issue. If needed, we can reopen it, of course.
