### ISSUE TITLE
Update Novdoc/SUSEDoc to disallow screen in entry

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#198]
Screens often need quite a bit of space. When they are nested inside a table they most often don't get that space.
We could do this via the Style Guide (informal) or via the DTD (formal).

Not sure if anyone else agrees with the latter approach... @tomschr, what do you think?

**Comment by tomschr** [comment]
I think we should discuss that on our mailing list.

Here are some of my pros and cons to disallow `<screen>` inside `<entry>`:

## Cons

* Maybe we have some future documentation where it is really needed?
* Reader should be allowed to use it, but is responsible for the content
* Linebreaks shouldn't be an issue, as the transformation should taken care of

## Pros

* Screens can occupy too much space
* Limit possible amount of elements, easier to handle
* Good connection between our style guide (informal) and our schema (formal).

Hmn, thinking about this... should we really disallow things just because it could "potentially looks bad"? In that case we should probably disallow more things. :grin:

It's always difficult to find a good balance between all these conflicting factors. Personally, ATM I'm more in favor to allow `<screen>` inside `<entry>` than do forbid it. Just because there may be cases where we shouldn't restrict writers too much.

However, I see your point. What about an additional step *after* validation which checks for some styleguide issues? Let's call it "layout validation" for the sake of simplicity.

In our example, this layout validation could count the maximum characters inside a screen and compare it to an "allowed" maximum value. If the first value is smaller than the second, everything is fine. If not, we can output a warning.

**Comment by sknorr** [comment]
> * Maybe we have some future documentation where it is really needed?

I think that in fact we have current documentation using this. E.g. Joseph's recent SuMa question (issue #116) sounded like he was using screens within a table. On IRC, he explained this request like this:
> What about an additional step after validation which checks for some styleguide issues? Let's call it "layout validation" for the sake of simplicity.

We have the style checker for this. So, we should use it. No need for an additional "layout validation" step, I think. The only issue with the style checker is that people (even me) tend to run it too rarely.

**Comment by tomschr** [comment]
This issue was moved to openSUSE/geekodoc#2
