### ISSUE TITLE
susedoc should allow all block elements as root element 

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/suse-xsl#230]
susedoc does not allow root elements such as <variablelist> in a file ( <!DOCTYPE variablelist ...>):

/data/git/doc-sle/build/.profiled/x86_64_zseries_power_aarch64_sles/common_docupdates_ga_i.xml:2:191: error: element "variablelist" not allowed here; expected element "info", "title", "titleabbrev" or "varlistentry"

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE variablelist
    [
      <!ENTITY % entities SYSTEM "entity-decl.ent">
        %entities;
    ]>

 Is it possible to allow any kind of block element as root element?

**Comment by tomschr** [comment]
@fsundermeyer This has nothing to do with what root elements are allowed or disallowed in our SUSEDoc schema.

I validated successfully the single file `common_docupdates_ga_i.xml` with jing and oXygen, both profiled and unprofiled without any problems.

The problem is `tuning_docupdates.xml`, [line 184](https://github.com/SUSE/doc-sle/blob/develop/xml/tuning_docupdates.xml#L184): There is already an `variablelist` element, but the included file contains it too. That's why there is an validation error, because there can't be a child element `variablelist` inside another `variablelist`.
