### ISSUE TITLE
Standardize on DB5 Stylesheet, Improve "Build Process"

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-xsl#262]
To ease development and maintenance, these things needs to be fixed:
- [ ] create a `catalog.d` directory to hold the new `suse-xsl-stylesheets.xml` catalog file.
- [ ] change the Makefile to build the non-namespaced stylesheets from the namespace aware
- [ ] migrate to DB5 stylesheets (see #95) as default

**Comment by sknorr** [comment]
Update, after Toms & I discussed:

* SUSE2020 styles will be DocBook 5 only (whenever they hit because we still have a redesign of unknown proportions in the way of that)
* There will be no changes to Makefile, except when we develop the new styles we won't need it because we only do DB5 styles.
* There is a catalog.d directory already.

Closing.
