### ISSUE TITLE
Create a style for result

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#286]
`<result>` is an element that can be used to mark up:

1. an intermediate result of a `<step>`, i.e. as the last element within step
2. the final result of a `<procedure>`, i.e. as the last element of a procedure

GeekoDoc already allows both uses but our stylesheets have display issues, so the element is not really usable yet: e.g. in FO, usage (1) outputs the literal source code, usage (2) does not have any output.

This one probably requires a mockup.

**Comment by cwickert** [comment]
As @jsetz11 is no longer with the team, can we please get this rolling again? I consider this important because one of the first feedback @jfaltenbacher gave about our docs is that our procedures should end with some kind of status or success-story, e.g. "You have sucessfully done foo". As we are to use procedures far more often in the future, this is becoming pressing.

**Comment by tomschr** [comment]
@cwickert See a first draft in PR #430.

**Comment by tomschr** [comment]
As we don't support EPUB anymore, this is closed as won't fix.
