### ISSUE TITLE
Part abstracts are cut off without continue link

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/suse-xsl#295]
At the beginning of a part (HTML at least)a "mini TOC" including the abstracts of the chapters is shown. Abstracts are cut of after a definded number of characters, e.g.

[...] In this way, a point-in-time copy o…

I have two issues with this approach:

1. An abstract should not be cut off in the middle of a word, probably not even in the middle of a sentence.
2. Please add a "continue", "read more",... (whatever you want to name it) link at the end of the abstract

Also see
https://bugzilla.suse.com/show_bug.cgi?id=1019978

**Comment by sknorr** [comment]
There are actually 2 behaviors here:

1. There is no actual "abstract" -> in that case, the first "para" is used; if it is longer than a defined number of characters, it is cut off. I can optimize that behaviour to not cut in the middle of words (by checking for spaces), but not cutting in the middle of a sentence is hard with XSLT.

2. If there is an "abstract," it is always printed in full fidelity. (Though that behavior could still be buggy for DocBook 5 -- I need to check.)

---
As to the "Continue" link: Not sure it really makes sense because there is such a link *above* the teaser text in question (i.e. the link to the respective chapter). Then again, it might make sense to be as obvious as possible.

**Comment by sknorr** [comment]
Stupid ideas of mine:

* It is not particularly important to cut off after the same number of characters in each case.
* Our current text-cutoff mechanism generates complete nonsense for xrefs. I think we could fix that by going through each actual text() individually, until we reach the requisite number of chars. A special no-\<a\>-for-xref mode might help too.
* I almost think that avoiding cutting in the middle of sentences might even be harmful because people might expect the end of the paragraph there. Also, some sentences are very long.
* Continue link is good but it should not be as prominent as the chapter title -- maybe dark gray + underline?

**Comment by tomschr** [comment]
I would say, this can be solved with these ideas:

* Tell our writers to write shorter paragraphs in an abstract. This would have the benefit of reusing it in different parts of the document.
* Raise the number in the parameter `onpage.teaser.length` (by default 300).

For these reasons, I don't think this is something that needs to be solved in XSLT.

**Comment by janajaeger** [comment]
More info on this in the styleguide ... https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-outline - check the "abstract" list item.
