### ISSUE TITLE
Too much spacing between command and option

### ISSUE THREAD

**Issue by svenseeberg** [openSUSE/suse-xsl#357]
With an additional space character between command and option tags the distance between both is too large. See SLE 15 "SCA Command Line Tool" (sec.admsupport.sca.tool).

![image](https://user-images.githubusercontent.com/15197000/34213065-7b2f1a14-e59e-11e7-9911-024ab764ef6f.png)

**Comment by sknorr** [comment]
I think the solution here is to just use `<command>some-command --my-option <replaceable>VALUE</replaceable></command>` rather than `<command>some-command</command> <option>--my-option <replaceable>VALUE</replaceable></option>`.

Personally, I think this is a WONTFIX, but I am leaving it open for now anyway...

Related: https://github.com/SUSE/doc-styleguide/issues/63

**Comment by janajaeger** [comment]
Wontifx it is, then.
