### ISSUE TITLE
Add clickable links for man pages 

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#374]
The following is copied from http://bugzilla.opensuse.org/show_bug.cgi?id=1104266:

> Documentation Feature:
A nice feature addition to the html documentation would be to make any
reference to a man page active.  Fore example, "man 1 journalctl" would be an
active link to http://man7.org/linux/man-pages/man1/journalctl.1.html.'

Not sure if this is something for our stylesheets or would also need to be implemented in DAPS, should we decide to go for this.

**Comment by tomschr** [comment]
Technically, it's possible. DocBook-wise, you need a [`citerefentry`](https://tdg.docbook.org/tdg/5.1/citerefentry.html), an inline element (inside `para`), in your code:

```xml
<para>... <citerefentry>
  <refentrytitle>journalctl</refentrytitle>
  <manvolnum>1</manvolnum><!-- optional -->
 </citerefentry>
   ...
</para>
```

Some things to think about:

* [ ] add `citerefentry` to GeekoDoc (easy!); currently, this element is disabled;
* [ ] define a default link for manpages like the one above (if possible, but should be easy); this could be implemented through a XSLT parameter;
* [ ] use an XLink in `citerefentry` if your manpage is NOT available in the default manpage. Something link like this:

```xml
<citerefentry xlink:href="http://man.example.org/man4/foofoo>
  <refentrytitle>foofoo</refentrytitle>
  <manvolnum>4</manvolnum>
 </citerefentry>
```

@taroth21, @sknorr: Would that work?

**Comment by tomschr** [comment]
> use this structure throughout all of our documentation (cumbersome? hard?)

Just to have some numbers: I've used `egrep` to find all manpage related lines.

```shell
$ egrep "man[ ]?page" xml/*.xml | wc
    176    1466   14691
```

**Comment by sknorr** [comment]
I really would not want to do that kind of markup.

I'd be a lot happier if we could get away with sth. like:

* `<citetitle role="man">journalctl(1)</citetitle>` or
* `<command role="man">man 1 journalctl</command>`


The DC file should then allow picking a man page URL scheme via a string param.

**Comment by tomschr** [comment]
> I really would not want to do that kind of markup.

It's not my invention. This is the standard way how DocBook does it. Not sure if we should try to "circumvent" that.

**Comment by sknorr** [comment]
> It's not my invention. This is the standard way how DocBook does it. Not sure if we should try to "circumvent" that.

Makes no real difference whether DocBook upstream invented this bloated syntax with \<incrediblylongandobtusetagnames/> or whether someone else did.

> Apart from that, your notation allows several ways to write this manpage reference. It's not standardized, be it citetitle or command => no consistency.

We just pick one of these two ways and only support one of these two ways -> bam, consistency. The style guide documents which one we went for and sdsc will be taught to flag the ones formatted differently and tell people they're doing it wrong *!*
No?

**Comment by tomschr** [comment]
Ok, let's summarize what we have:

* `<citerefentry>`
  * Pros:
     * "blessed" by DocBook and the stylesheets
     * high consistency at validation time (no ambiguity)
     * no need to adapt stylesheets and other tools (it's already there)
  * Cons
     * a bit more verbose (however, `manvolum` is optional)
     * our documents needs to be corrected
     * element(s) have to be enabled in GeekoDoc

* `<command role="man">` or `<citetitle role="man">`
   * Pros:
     * a bit easier to write than `<citerefentry>`
     * already there in our documentation
     * no need to adapt GeekoDoc
   * Cons:
     * consistency can only be reached by style checker, but not through validation
     * Stylesheets, style checker etc. has to be adapted as well
     * not blessed, nor standardized by DocBook & the stylesheets
     * our documents have to be adapted anyway

Looking at this overview, I would prefer the `<citerefentry>` way, because:

* It's "standardized" and already implemented by the stylesheets. Why reinvent the wheel?
* Yes, it is slightly more verbose than Stefan's proposal, but with a decent XML editor, it's not an issue. If you type `citeref...` in your XML editor, it will add the `refentrytitle` automatically for you. That's why we have schemas! :wink: 
* If you have this inconsistency and ambiguity with `command` or `citetitle` you can never be sure if you  have correct values. This is not the case with `<citerefentry>`. As style checking is optional, you can't rely on correct values. You can easily forget to run the stylechecker. This leads to situations, where you have inconsistent values and you can't really deal with that in the stylesheets. Conclusion: in the worst case, you can't really create a link to its manpage.

**Comment by sknorr** [comment]
> It's "standardized" and already implemented by the stylesheets. Why reinvent the wheel?

The linking functionality is not actually implemented. I don't see how you can count that as a positive aspect here -- one way or another, we'd have to implement this.


> Yes, it is slightly more verbose than Stefan's proposal, but with a decent XML editor, it's not an issue. If you type citeref... in your XML editor, it will add the refentrytitle automatically for you.

Your editor does. Good for you! Mine doesn't (I could teach it but still).
Meanwhile, the drawback that this is another one of these hard-to-read XML eyesores remains.


> If you have this inconsistency and ambiguity with command or citetitle you can never be sure if you have correct values.

As I said before, we could just pick *one* of the two (either \<citetitle/> or \<command/>).

> This is not the case with <citerefentry>. As style checking is optional, you can't rely on correct values. You can easily forget to run the stylechecker. This leads to situations, where you have inconsistent values and you can't really deal with that in the stylesheets. Conclusion: in the worst case, you can't really create a link to its manpage.

Since this relies on an external service, you need to check the link created in *all* cases anyway. There is never a guarantee that if we guess `https://some.external-man-page-server.com/foo.5.html`, it will work. Being able to validate whatever XML construct is behind this actually does not buy us much beyond a pretty but possibly non-functional link.

**Comment by taroth21** [comment]
Phew, a lot of arguments and pros and cons...

If you want my $0.02: I fear that both solutions (```<citerefentry>``` or ```role="man"```) will only be used by 10-20% of our authors. :( If the ```xlink:href``` attribute is only necessary if the URL for the man page is different from the default one (defined by a stylesheet param), it might work, but still the markup is far from intuitive with regards to the action I want to do (pointing to a man page).
Personally, I would prefer the ```role="man"``` solution but if we go for that, we should just allow one way. But I also doubt that many authors will run a) the stylechecker b) the linkchecker to check if we end up with consistent and usable links. -> Even more (obnoxious) tasks that end up with the ones who deliver localization drops or online-docs, while I would prefer that the individual authors stumble across problems - but that's a problem with all our 'post-editing' tools.

Maybe more important and not mentioned already: What happens to those man page links (however they would be implemented) when we need to convert the DB5 sources to DocBook or AsciiDoc?

**Comment by tomschr** [comment]
> The linking functionality is not actually implemented. I don't see how you can count that as a positive aspect here -- one way or another, we'd have to implement this.

That's the whole point: sorry Stefan you're wrong, it **IS** already implemented!

This was one of the features of XLink that came with DocBook 5. It's is already recognized though the DocBook XSL stylesheets. Actually, you can use that for all inline elements, not only for `<citerefentry>`.

However, there is one culprit: currently, XLinks in most inline elements are disabled in GeekoDoc. So for `command` or `citetitle`. It will work for `citerefentry` once it is enabled.

> Your editor does. Mine doesn't (I could teach it but still).
Meanwhile, the drawback that this is another one of these hard-to-read XML eyesores remains.

Well, why do you blame the messenger (XML format) if you use a shitty editor which doesn't understand RNG? :wink: 
But seriously, there are other DocBook constructs which are also very verbose, but you use it every day and never protested. Why is it different here?


> >   If you have this inconsistency and ambiguity with `command` or `citetitle` you can never be sure if you have correct values.
>
> As I said before, we could just pick one of the two (either `<citetitle/>` or `<command/>`).

That's not the point. It's **not** about picking either one. It's about the **implicit structure** that is highly 
ambiguous. Consider these alternatives that I've found in our SLE documentation:

```xml
<command>man zypper</command>
<command>man 8 zypper</command>
<command>zypper</command>
<command>zypper (8)</command>
<quote>apparmor(7)</quote>
<command>netconfig</command>(8)
```

From a consistency point of view, these are awful. I would really avoid those implicit structures.

All the above examples are valid against GeekoDoc. This is **bad** as it gives no hints to our authors how to do it right. No author can remember which implicit structure is the correct one, regardless if it's written in the styleguide or not. It also won't help if stylechecker knows it or not. It's already too late. Such a thing has to be *checked during validation* with GeekoDoc.

On the other side, with  `<citerefentry>`, there are no implicit structures, only explict ones. Although I agree, the element name is suboptimal, but that's the way it is in DocBook.

The other issues is, how you turn your implicit structure into valid links. Try to parse the above implicit structure with XSLT. Good luck with that, I'll buy you a Schnecke to ease your pain. :wink: 

> Since this relies on an external service, you need to check the link created in all cases anyway. [...]
> Being able to validate whatever XML construct is behind this actually does not buy us much beyond a pretty but possibly non-functional link.

That's true. But this has nothing to do with the XML markup per se. However, your concerns are addressed by `daps linkcheck`. That should take into account any XLinks.

**Comment by tomschr** [comment]
> I fear that both solutions (<citerefentry> or role="man") will only be used by 10-20% of our authors. :(

Maybe, maybe not. The current state is, that *some* markup is already used by our authors, but it's very inconsistent. As I've pointed out in my example from https://github.com/openSUSE/suse-xsl/issues/374#issuecomment-413449198, you can see lots of variants.

IMHO, I think, the **lack of a standard markup** is one of the major issues here. If we agree to one markup, document it in the styleguide & Hitchhiker, announce it on doku-intern, at least our writers are able to find the right solution. Of course, not all will probably use it, but at least it's there and can be found.

> But I also doubt that many authors will run a) the stylechecker b) the linkchecker to check if we end up with consistent and usable links. -> Even more (obnoxious) tasks [...]

That's why I vote for `citerefentry`, because you don't have to think about more "(obnoxious) tasks". 

> What happens to those man page links (however they would be implemented) when we need to convert the DB5 sources to DocBook or AsciiDoc?

You need to adapt the conversion stylesheets. But you have to do it anyway, regardless of the method.

**Comment by sknorr** [comment]
So I noticed I had this draft comment still in my Drafts folder...


> That's the whole point: sorry Stefan you're wrong, it **IS** already implemented!

Half point taken.
My idea involved setting up the URL once, centrally and parsing out the
rest, whereas I think your idea means that people have to add an
xlink:href attribute everywhere in addition to the rest of the markup.


> Well, why do you blame the messenger (XML format) if you use a shitty editor which doesn't understand RNG? :wink: 

By your definition, most people use "shitty" editors, including most of
the outside people we want to make editing easier for (supposedly).

And then, while Oxygen does have RNG support, between the non-existent
desktop integration, sparse extension ecosystem, and XML reflowing
fuckups [1] it's pretty far from a perfect solution. Editors are
invariably trade-offs and always less than perfect in one way or another.

Note also that the point about inline XML eyesores is completely editor-
independent. (You won't catch me arguing for a re-introduction of
\<indexterm/> constructs in our books either.)


> But seriously, there are other DocBook constructs which are also very verbose, but you use it every day and never protested. Why is it different here?

*
\<theelements>\<herehaveespeciallylongnames>\</andarecomicallydeep>\<totheircontent/>
* we have a comparison to the much more lightweight structure(s) we use
currently
* the issue solved is pretty small

It also wouldn't be such an issue if DocBook provided a suitably short
construct like `<manpage sect="3">command</manpage>` that would allow us
to get away with very little overhead.
Alas.

There are other XML constructs we could simplify, also true. But that is
not the point of this bug.


>> As I said before, we could just pick one of the two (either `<citetitle/>` or `<command/>`).
> 
> That's not the point.

It was one of your points.


> It's **not** about picking either one. It's about the **implicit structure** that is highly 
> ambiguous. Consider these alternatives that I've found in our SLE documentation:

All of these will remain valid, the only thing that *might* help weed
them out *eventually* is the style checker. In essence, whatever we
choose, the style checker is our only hope of consistency, I think.


> The other issues is, how you turn your implicit structure into valid links. Try to parse the above implicit structure with XSLT. Good luck with that, I'll buy you a Schnecke to ease your pain. :wink: 

That is an easily earned pastry gastropod. Processing plain text
with XSLT is by no means great but these seem like rather solvable
issues.

E.g.

```
$input='command(1)'

$mancommand = normalize-space(substring-before($input,'('))
$mansection =
normalize-space(substring-before(substring-after($input,'('),')'))
```


> That's true. But this has nothing to do with the XML markup per se. However, your concerns are addressed by `daps linkcheck`. That should take into account any XLinks.

So, if I understand correctly,

* stylecheck which at least some people do and which takes some time but
usually much less than linkcheck = inacceptable,
* linkcheck which absolutely no one does and which takes forever  =
acceptable

..?

I looked at your proposal again and indeed you want every man page to be
linked explicitly. I'll point out a few issues with that:

1. This is, again, extra work.
1. It leads to inconsistency within the document and it makes it harder
to switch to a different provider if one goes down.
1. The onus on picking a man page provider is on the author. Most of us
run ad blockers etc., so e.g. we don't even normally notice if the man
page provider runs unsuitable advertising (which is an issue because man
page providers tend to be more sketchy on average than regular
open-source doc pages we link to usually). Picking a default provider
means we can vet better.


[1] These fuckups happen to absolutely *everyone* using Oxygen and
besides bloating Git, they destroy all hope of being able to do proper
git blames.

**Comment by janajaeger** [comment]
> And last but not least: if it makes life too complicated for authors, stylesheet maintainers or project leads, there is also the option to turn down this enhancement request (although I really like it from the user perspective). ;)

Long story short - there is no pretty solution to this :( The extra amount of work and care that has to be put into isn't justified by getting a few more links (that could get broken). Therefore closing this.
