### ISSUE TITLE
intra-xrefs (used especially in single-HTML) are confusing, find a better way to create references to other books

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-xsl#424]
## Problem Description

See https://bugzilla.suse.com/show_bug.cgi?id=1178569#c2.

## Expected Behaviour

Find a better way to solve this as this obviously confuses people.

**Comment by stefanq** [comment]
I'm not "authorized to access bug #1178569".
WTH, what kind of privacy needs do you have with this?

**Comment by stefanq** [comment]
@sknorr  Thank you Stefan!
IMO the openSUSE project has a lot of legacies regarding communicating openly and unfortunately the never become aware of it. I'm with openSUSE since the 90ies, always found it to be a superior project and distribution, and I'm still waiting that they do the right steps to open for more and easy contribution so that the project can take off in terms of community contribution. Alone the fact that for the most interesting stuff and most direct contact to developers you have to cope with their mailing lists still makes me cringe all the time.
Sorry for going off topic that far.

**Comment by vmoutoussamy** [comment]
BTW we are now using some Public Bugzilla products for documentations issues. For instance: https://bugzilla.suse.com/buglist.cgi?list_id=13526478&product=PUBLIC%20SUSE%20Linux%20Enterprise%20Server%2015%20SP4&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=NORESPONSE&resolution=UPSTREAM&resolution=FEATURE&resolution=DUPLICATE&resolution=WORKSFORME&resolution=MOVED : )

**Comment by tomschr** [comment]
This is a current limitation of our toolchain. We are working on a solution for this in regards to SmartDocs, but for the time being this can't be solved easily.
