### ISSUE TITLE
`xref` renders as plain text

### ISSUE THREAD

**Issue by KucharczykL** [openSUSE/suse-xsl#443]
## Problem Description
The code below renders as plain text instead of a link:
```xml
<xref linkend="jsc-SLE-16552"/>
```

(Source at https://gitlab.suse.de/documentation/release-notes-sles/-/blob/15_SP1/xml/release-notes.xml#L3841)

![image](https://user-images.githubusercontent.com/31072879/144043372-d51f8ed0-dd0b-4569-8c45-7fd15303244f.png)

This only happens locally on my Tumbleweed installation:

Name           : suse-xsl-stylesheets
Version        : 2.99.20211129-26.1

## Expected Behaviour

The code is rendered as link, as can be seen here: https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP1/index.html#jsc-SLE-16552-1

**Comment by sknorr** [comment]
This issue occurs because the new stylesheets no longer support DocBook 4's `@id`, and instead look for DocBook 5's `@xml:id` attributes. This is an intended change that has simplified code in quite a few places already. As such, I think this is a wontfix.

* If you need to update to the new stylesheets, please update to DocBook 5 along with that. For release notes content, that operation should essentially consist of fixing the document head and then a sed operation like `sed -ir -e 's/<ulink href=/<link xlink:href=/g' -e 's/<\/ulink/<\/link/g' -e 's/ id=/ xml:id=/g'`.

(cc @tomschr @fsundermeyer )
