### ISSUE TITLE
l10n issues

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/suse-xsl#458]
The following issues were found during the localisation of SES 7.1. I assume they are valid for both, 2021 and 2022 stylesheets.

* [x] ZH-CN / ZH-TW
- PDF bookmark format requires syntax edit Glossary sorting in pinyin request.
- Automatic glossary sorting is switched off in the stylesheets.

* [ ] ZH-TW
- PDF bookmark format requires syntax edit
- Date format on page ii needs to be modified. We can't find this string in the book files so assume it is set in gentext in DAPS.

* [x] FR-FR
There is a stray capital letter 'T' in the construct of the figure label. Needs to be removed.

---
Edit toms 2022-07-05: mark them as tasks and combine zh-cn/zh-tw

**Comment by tomschr** [comment]
@jfaltenbacher Can you answer the about the date format? Or do you know about sorting in Chinese? Thanks!

**Comment by jfaltenbacher** [comment]
Chinese date format is yyyy-mm-dd (as in ISO 8601)

Because of the glossary sorting. I remember having the same problems at my former job and we always had issues with the glossary, but could never solve them because of missing language skills. I don't remember if we just left the glossary as it came out or if we removed it from the translated books in the end. From what I remember the sorting was alphabetically but not really working well for the asian languages
