### ISSUE TITLE
Remove the SUSE address from the stylesheets themselves

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#96]
Currently, the address of SUSE is added to our PDF books through the stylesheets. Hindsight 20/20 says this is a dumb idea:
-   If someone else wants to use our stylesheets, they automatically get a SUSE address in there
-   If SUSE's address changes, we have to get a new stylesheets package out instead of being able to fix the affected books (see issue #34 and [bsc#929630](https://bugzilla.suse.com/show_bug.cgi?id=929630))

If we want to keep the address, it might be good to look at two possible solutions:
1.  DB5's `<address/>` element (see [TDG](http://docbook.org/tdg5/en/html/address.html)), nested within the `<info/>` element of the set or book. The only drawback I see is that the `<address/>` element is usually formatted verbatim (a bit undesirable for formatting reasons). Also, I am not sure if that address is automatically output then somewhere (undesirable, but we can obviously work around that in the stylesheets).
2.  Use the DocManager to roll our own solution.

**Comment by sknorr** [comment]
@tomschr What do you say?

**Comment by tomschr** [comment]
Isn't the parameter `company.address` enough for this purpose?

This should give users enough opportunities to customize the address.

**Comment by sknorr** [comment]
The parameter? That is true, however, parameters always feel a bit volatile, since it is so easy to forget/accidentally remove them.

I think it is also a bit of coding hygiene. And after thinking about it and seeing the issues with our current approach, I think the books are the best place for this.

Sure, we also have SUSE logos in our stylesheets, but I think the more we can put in the books themselves, the better, right?

**Comment by tomschr** [comment]
The (former) design of the SUSE stylesheets are based on Novdoc. As we all know, it is a subset of DocBook and doesn't allow many variations. As such, things like `<address>`, namespaces etc. were not taken into account.

Now the situation has changed as we switched to DocBook5. I agree, we could adapt some design decisions and move some things into the XML rather than keep them as parameters.

However, we should first agree on a common basis of the SUSEDoc schema before we change the stylesheets. Related to openSUSE/daps#254.
